src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/FiveImpl.java

smallest has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/FiveImpl.java

solveSum has done!

---

src/main/java/com/org/ita/kata/implementation/MyroslavaVynokur/SIxImpl.java

Myroslava vynokur/nba cup

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/FiveImpl.java

perimeter have done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/FiveImpl.java

Yaroslav tarasovych/zeros

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SIxImpl.java

Yaroslav tarasovych/mean and variance

---

src/main/java/com/org/ita/kata/implementation/nastiakomarenko/EigthImpl.java

divisibleBy

---

src/main/java/com/org/ita/kata/implementation/nastiakomarenko/EigthImpl.java

twoDecimalPlaces

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/FiveImpl.java

gap has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SIxImpl.java

stockSummary has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SIxImpl.java

nbaCup has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SIxImpl.java

f has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SIxImpl.java

Yaroslav tarasovych/balance

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SIxImpl.java

Yaroslav tarasovych/find nb

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SevenImpl.java

Yaroslav tarasovych/series sum

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SevenImpl.java

Yaroslav tarasovych/new avg

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/liters

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/divisible by

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

twoDecimalPlaces has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/wilson prime

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/string to number

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/count positives sum negatives

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/square or square root

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

Yaroslav tarasovych/converter

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/EigthImpl.java

getVolumeOfCuboid has done!

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/FiveImpl.java

Yaroslav tarasovych/artificial rain

---

src/main/java/com/org/ita/kata/implementation/nastiakomarenko/SIxImpl.java

stockSummary

---

src/main/java/com/org/ita/kata/implementation/YaroslavTarasovych/SevenImpl.java

whereIsHe has done!

---

src/main/java/com/org/ita/utils/Buffer.java
src/main/java/com/org/ita/utils/Reader.java

Add NumberFormatException to readDouble, readInt, readLong, readFloat

Add implementation readBigInteger(

---

src/main/java/com/org/ita/utils/StartTask.java

Yaroslav/find nb/runner

---

src/main/java/com/org/ita/utils/StartTask.java

runPerimeter has done!

---

src/main/java/com/org/ita/kata/implementation/nastiakomarenko/EigthImpl.java

change method mpg

---

src/main/java/com/org/ita/kata/implementation/nastiakomarenko/SIxImpl.java

changes in method mean

---

src/main/java/com/org/ita/kata/implementation/nastiakomarenko/SIxImpl.java

changes in variance method

---

src/main/java/com/org/ita/kata/implementation/MyroslavaVynokur/FiveImpl.java
src/test/java/implementation_test/FiveImplTest.java

change FiveImpl testGap & testGapNull time-out to 1600

add correction Gap & Zeros

---

src/test/java/task_runner_menu_test/TaskRunnerMenuTest.java
src/test/java/task_runner_menu_test/data_provider_menu/TaskRunnerMenuData.java

add TaskRunnerMenuTestData.java

add TaskRunnerMenuTest.java

---

src/main/java/com/org/ita/utils/Buffer.java
src/test/java/utils/BufferTest.java
src/test/java/utils/data_provider_buffer/BufferData.java

add getValidIntFromUserInputTestData

add readStringArrTestData
